; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = COM6
monitor_port = COM6
lib_deps = bodmer/TFT_eSPI
board_build.f_cpu = 240000000L

upload_flags =
    --before=default_reset
    --after=hard_reset

build_flags =
    -DUSER_SETUP_LOADED=1
    -DST7735_DRIVER=1
    -DST7735_GREENTAB=1
    -DTFT_INVERSION_ON=1
    -DTFT_WIDTH=128
    -DTFT_HEIGHT=160
    -DTFT_CS=5
    -DTFT_DC=27
    -DTFT_RST=4
    -DTFT_MOSI=23
    -DTFT_SCLK=18
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DSPI_FREQUENCY=4000000